// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241106000920_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Authentication.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.Narrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GPTConversationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerCampaignId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCampaignId");

                    b.ToTable("Narrators");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.NarratorMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerNarratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerNarratorId");

                    b.ToTable("NarratorMessages");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("Notes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("OwnerCampaignId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCampaignId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.Files.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerCampaignId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCampaignId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.Campaign", b =>
                {
                    b.HasOne("Domain.Entities.Authentication.ApplicationUser", "OwnerUser")
                        .WithMany("Campaigns")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.Narrator", b =>
                {
                    b.HasOne("Domain.Entities.Campaigns.Campaign", "OwnerCampaign")
                        .WithMany("Narrators")
                        .HasForeignKey("OwnerCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerCampaign");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.NarratorMessage", b =>
                {
                    b.HasOne("Domain.Entities.Campaigns.Narrator", "OwnerNarrator")
                        .WithMany("Messages")
                        .HasForeignKey("OwnerNarratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerNarrator");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.Session", b =>
                {
                    b.HasOne("Domain.Entities.Campaigns.Campaign", "OwnerCampaign")
                        .WithMany("Sessions")
                        .HasForeignKey("OwnerCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerCampaign");
                });

            modelBuilder.Entity("Domain.Entities.Files.Image", b =>
                {
                    b.HasOne("Domain.Entities.Campaigns.Campaign", "OwnerCampaign")
                        .WithOne("BannerImage")
                        .HasForeignKey("Domain.Entities.Files.Image", "OwnerCampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OwnerCampaign");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.ApplicationUser", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.Campaign", b =>
                {
                    b.Navigation("BannerImage");

                    b.Navigation("Narrators");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.Campaigns.Narrator", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
